apiVersion: v1
kind: ConfigMap
metadata:
  name: travelforge-config
  namespace: travelforge
data:
  PORT: "5000"
  NODE_ENV: "production"
  LOG_LEVEL: "info"

  PUBLIC_SCHEME: "http"
  PUBLIC_HOST: "travelforge.test"
  APP_BASE_URL: "http://travelforge.test"

  GRAFANA_ROOT_URL: "http://travelforge.test/grafana/"
  PROMETHEUS_EXTERNAL_URL: "http://travelforge.test/prometheus/"

  ALLOWED_ORIGINS: "http://travelforge.test,https://travelforge.test,http://localhost:3000,http://localhost:3001"

  GIGACHAT_SCOPE: "GIGACHAT_API_PERS"
  GIGACHAT_TIMEOUT: "60"
  GIGACHAT_TLS_VERIFY: "1"