apiVersion: v1
kind: Service
metadata:
  name: travelforge-frontend
  namespace: travelforge
  labels:
    app.kubernetes.io/name: travelforge-frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: travelforge-frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
