apiVersion: v1
kind: Service
metadata:
  name: travelforge-grafana
  namespace: travelforge
  labels:
    app.kubernetes.io/name: travelforge-grafana
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: travelforge-grafana
  ports:
    - name: http
      port: 3000
      targetPort: 3000
