apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-to-backend
  namespace: travelforge
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: travelforge-backend
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: travelforge-prometheus
      ports:
        - protocol: TCP
          port: 5000
