apiVersion: v1
kind: Secret
metadata:
  name: travelforge-secret
  namespace: travelforge
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_LONG_RANDOM_SECRET"
  GIGACHAT_CLIENT_ID: "019ad692-c51b-7e19-8294-bed25b837281"
  GIGACHAT_SECRET: "9f85b8e0-a182-49d8-a886-031243866e3c"
