apiVersion: v1
kind: Secret
metadata:
  name: travelforge-secret
  namespace: travelforge
type: Opaque
stringData:
  JWT_SECRET: "CHANGE_ME_LONG_RANDOM_SECRET"
  GIGACHAT_CLIENT_ID: "CHANGE_ME_GIGACHAT_CLIENT_ID"
  GIGACHAT_SECRET: "CHANGE_ME_GIGACHAT_SECRET"
